Repository HabanaAI/vllm-fork, pull requests merged in 2024-10, with the labels that each got.

#315 Fixed lora manager tests
  tests/lora/conftest.py
  tests/lora/test_lora_manager_hpu.py
Labels: habana

#348 Lora Mask based on lora index
  vllm/worker/habana_model_runner.py
Labels: habana

#293 remove import vllm._C for hpu
  vllm/_custom_ops.py
Labels: intel

#287 Add AliBi to supported features in README_GAUDI.md
  README_GAUDI.md
  docs/source/getting_started/gaudi-installation.rst
Labels: habana

#303 Implement custom moe op for Mixtral
  vllm/hpu/ops.py
  vllm/model_executor/layers/fused_moe/layer.py
Labels: habana

#396 Workaround for OOM during loading llama-405
  vllm/model_executor/models/llama.py
Labels: bug, habana

#406 Add HPU specific arguments to benchmark_throughput
  benchmarks/benchmark_throughput.py
Labels: habana

#412 Remove if blocks smaller than bs in generate_decode_buckets
  vllm/worker/hpu_model_runner.py
Labels: habana

#414 Remove CPU sync before Sampler
  vllm/model_executor/layers/sampler.py
Labels: habana

#423 Update README_GAUDI about fp8 calibration procedure
  README_GAUDI.md
Labels: documentation, habana

#428 Set vllm-hpu-extension to 341a77f
  requirements-hpu.txt
Labels: habana

#424 Contiguous PA
  requirements-hpu.txt
  vllm/worker/hpu_model_runner.py
Labels: habana

#246 sarkar/Add htrandom generator for hpu
  vllm/model_executor/sampling_metadata.py
Labels: habana

#427 Fix one_hot bug in torch compile mode
  vllm/worker/hpu_model_runner.py
Labels: bug

#162 initial works on enabling automatic prefix caching
  requirements-hpu.txt
  vllm/attention/backends/hpu_attn.py
  vllm/attention/ops/hpu_paged_attn.py
  vllm/worker/hpu_model_runner.py
Labels: external

#429 Add fp8 test to jenkins CI
  .jenkins/lm-eval-harness/configs/Meta-Llama-3.1-8B-Instruct-fp8.yaml
  .jenkins/lm-eval-harness/configs/models-fp8.txt
  .jenkins/lm-eval-harness/test_lm_eval_correctness.py
  .jenkins/test_config.yaml
Labels: enhancement, habana
