Repository HabanaAI/vllm-fork, pull requests merged in 2024-11, with the labels that each got.

#478 Add FP8 TP=2 scenario to Jenkins CI
  .jenkins/test_config.yaml
Labels: enhancement, habana

#504 Add FP8 inference procedure
  README_GAUDI.md
Labels: documentation, habana

#530 [bucketing overhaul 2/n] Delegate bucket management to HPUBucketingContext
  vllm/worker/hpu_model_runner.py
Labels: habana

#430 Add HPU information to collect_env script
  collect_env.py
Labels: habana
